services:

  reverse-proxy:
        image: nginxproxy/nginx-proxy:1.7-alpine
        container_name: "reverse-proxy"
        volumes:
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: "always"
        networks:
          - net
          - dbnet
          - redisnet
        ports:
          - 80:80
          - 443:443
        depends_on:
          - flask

  flask:
    build: .
    restart: always
    secrets:
      - db-password
      - mail-password
    volumes:
      - ./uploaded_datasets:/home/qrater/app/static/datasets/uploaded
      - ./datasets:/home/qrater/app/static/datasets/preloaded
      # Extra volumes in compose.override.yaml
    environment:
      - FLASK_APP=qrater.py
      - REDIS_URL=redis://redis:6379/0

    env_file:
      - qrater.env
    ports:
      - 8080:5000
    networks:
      - dbnet
      - redisnet
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.0.43
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_DATABASE=qrater
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  redis:
    image: redis:6.2.20-alpine
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - redisnet
    expose:
      - 6379

  worker1:
    build: .
    entrypoint:
      - /usr/local/bin/_entrypoint.sh
      - rq
      - worker
      - --url
      - redis://redis:6379/0
      - qrater-tasks
    restart: always
    secrets:
      - db-password
      - mail-password
    volumes_from:
      - flask
    environment:
      - FLASK_APP=qrater.py
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - qrater.env
    networks:
      - dbnet
      - redisnet
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker2:
    build: .
    entrypoint:
      - /usr/local/bin/_entrypoint.sh
      - rq
      - worker
      - --url
      - redis://redis:6379/0
      - qrater-tasks
    restart: always
    secrets:
      - db-password
      - mail-password
    volumes_from:
      - flask
    environment:
      - FLASK_APP=qrater.py
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - qrater.env
    networks:
      - dbnet
      - redisnet
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  db-data:
  certs:
  html:
  vhost:
  dhparam:

secrets:
  db-password:
    file: db-password.txt
  mail-password:
    file: mail-password.txt

networks:
  dbnet: {}
  redisnet: {}
  net: {}
